### ISSUE TITLE
cant get the esx_addon_phone to work

### ISSUE THREAD

**Issue by JessicaxD** [N3MTV/gcphone#10]
am srry but i cant get it to work, the phone is not oppeing, did i put it in wrong? do i need both resources file or just the esx_addon_phone? an the src_htmlphone folder do i just drag it in or do i need to put it in the esx_addon_phone?

**Comment by Oldarorn** [comment]
You need to download https://github.com/N3MTV/gcphone/releases/download/V2_alpha_0/gcphone.zip

and start both resources.

drop gcphone in your resources folder and esx_addons_gcphone into your [esx] folder.

Then start both resources in server.cfg

**Comment by JessicaxD** [comment]
ahhh okei thank you :)

**Comment by JessicaxD** [comment]
its not giving the police any alerts tho, its says in the rcon: Double alert ? Maj ├á jour ?

**Comment by Oldarorn** [comment]
It seems you've missed something then ! In which order are you loading the scripts ?

It must be like this : 

-gcphone
-esx_addons_gcphone

If the police doesn't take the call, take a look in html/static/config and check if it's written like this 

    {
      "display": "Police",
      "subMenu": [
        {
          "title": "Envoyer un message",
          "eventName": "esx_addons_gcphone:call",
          "type": {
            "number": "police"
          }
        }
      ]
    },

**Comment by Oldarorn** [comment]
Oh and... Load both scripts before jobs :) !

**Comment by JessicaxD** [comment]
is it anyway you can make it so ppl can hear you when you talk in the phone, like the ppl around you? or is that a nogo?

**Comment by Oldarorn** [comment]
There must be a solution about it, I haven't used the new version right now but you can search for something like this : 

`    NetworkSetVoiceChannel(infoCall.id + 1)
    NetworkSetTalkerProximity(0.0)`

and update NetworkSetTalkerProximity to the setting you wish

**Comment by JessicaxD** [comment]
hmmmm okei thanks :)

**Comment by CMDTelhada** [comment]
==== Enregistrement du telephone police => Alerta da Police
