### ISSUE TITLE
No output when running npm run build?

### ISSUE THREAD

**Issue by sazo2300** [N3MTV/gcphone#100]
Hi. I tried making the phone work with mouse interactions. It does work on the npm run dev enviroment. I cant compile it however (with and without my changes). When i run npm run build, i dont get the output folders? In static the js and css folders are missing. Am i building it wrong?

**Comment by Gannon001** [comment]
npm run build 
for générate file.

**Comment by sazo2300** [comment]
Where should the files be located? There is no js or css folder?

**Comment by Gannon001** [comment]
gcphone/resources/gccphone/html
src_htmlPhone/../resources/gccphone/html

(Sorry, I'm not sure I understand you)

**Comment by sazo2300** [comment]
Ye you were right. ../resources is the output folder. Thanks <3
