### ISSUE TITLE
Mouse testing issues

### ISSUE THREAD

**Issue by sazo2300** [N3MTV/gcphone#101]
Here are some bugs with the newest release (mouse support)
- Backspace and Esc no longer closes the phone
- All screens except the home screen sometime require many clicks for one action (example: try call a person. You have to click end call a lot of times to end the call)
- Clicking outside the phone will close it which is good. But after that, opening it again and clicking an app, or clicking anything in the phone also closes it

Maybe you already know all this, i just figured you might want someone to test it ^^
Thanks for everything you do!

**Comment by Gannon001** [comment]
Hi, Thanks for feedback
  * I have add Esc for close phone
  * I do not succeed in having the same result as you. 
  * Same, but a change left click by rigth ouside phone for close

**Comment by sazo2300** [comment]
Youre welcome! I love this resource ^^

- Esc seems to work to close phone. Super nice ^^ Will backspace to go back (like without mouse) be made too?
- Try calling someone with the phone. Then hang up on them. For me everytime it takes a lot of clicks before the button responds. (I can make a short clip if you want. Might also just be issue with my server)
- Not sure what you mean with the last one, but after i close one time outside phone, i have to restart resource to make it work again. (Can also make short clip of this one if it would help)

**Comment by SnowQT** [comment]
Hey, first thank you again for your amazing work on this last update.

i'm having pretty much the same issues that @sazo2300 reported just above but one!

>Top tweets are not being displayed in the "mouse support" version, they do when i use the one without it. (same db).

Have a nice day

**Comment by Gannon001** [comment]
> Top tweets are not being displayed in the "mouse support" version, they do when i use the one without it. (same db).

Thx, it fix

Do you have errors in the console for mouse problems? I do not have these problems on my side. So, I do not know where to look for the problem.

**Comment by sazo2300** [comment]
> > Top tweets are not being displayed in the "mouse support" version, they do when i use the one without it. (same db).
> 
> Thx, it fix
> 
> Do you have errors in the console for mouse problems? I do not have these problems on my side. So, I do not know where to look for the problem.

No errors. But i can check where the issue is maybe. I have an idea about its tied to amount of frames. Maybe you have a longer wait than 0 at the click nui event. If so, the more frames you have, the less chance it registers the click

**Comment by Gannon001** [comment]
I call SetNuiFocus for each frame.
https://github.com/N3MTV/gcphone/blob/a7d042b8c4b46f6e57256f824e890a42c76d5c86/resources/gcphone/client/client.lua#L92

I fix some elements, but I do not think it will correct the mouse problem.

If you find something, let me know

**Comment by sazo2300** [comment]
> I call SetNuiFocus for each frame.
> [gcphone/resources/gcphone/client/client.lua](https://github.com/N3MTV/gcphone/blob/a7d042b8c4b46f6e57256f824e890a42c76d5c86/resources/gcphone/client/client.lua#L92)
> 
> Line 92 in [a7d042b](/N3MTV/gcphone/commit/a7d042b8c4b46f6e57256f824e890a42c76d5c86)
> 
>  SetNuiFocus(useMouse, useMouse) 
> I fix some elements, but I do not think it will correct the mouse problem.
> 
> If you find something, let me know

Im testing a whole bunch now. One person in my server dont have the issue, so i think it might be due to cache. I deleted my cache and am redownloading cache from fivem now. Will report back after :)

Other issue now is when calling/getting call this shows up: https://image.prntscr.com/image/VHDacGS5QXWBUiJTc3YA9w.png
 Any idea why :o ?

**Comment by sazo2300** [comment]
Weird thing is, its only in all other views than the home screen

**Comment by Gannon001** [comment]
URL is not valide

U can add me to discord ? Gannon#0626

I need you for testing on my dev server

**Comment by sazo2300** [comment]
> URL is not valide
> 
> U can add me to discord ? Gannon#0626
> 
> I need you for testing on my dev server

Added you. Picture attached 
![VHDacGS5QXWBUiJTc3YA9w](https://user-images.githubusercontent.com/8972081/56083877-09a62980-5e2b-11e9-82a9-a1a760f90363.png)

**Comment by sazo2300** [comment]
Everything works perfectly, except for new contact still ^^

**Comment by sazo2300** [comment]
With #101

**Comment by sazo2300** [comment]
And backspace still buggy some places. Like inside message thread (before sending a message to someone)

**Comment by Gannon001** [comment]
I corrected.

**Comment by sazo2300** [comment]
Yep. Works flawless! Thanks <3

**Comment by izio38** [comment]
I have a click issue too. I can't click the modal to add messages on twitter for example.
Also, I can't see the `twitter` directory under `components` from the sources.
https://i.gyazo.com/d3909193288ceacb8327f75da549e95a.png
