### ISSUE TITLE
mysql jobs

### ISSUE THREAD

**Issue by elnax90** [N3MTV/gcphone#104]
gcphone is seaching job @ job_grades table insted of jobs table.

where do i change this in the configs?  
i cant find it anywhere!

waiting your news! 
Thank you!

**Comment by elnax90** [comment]
@Gannon001 sir can you provide me some assist?
thank you!

**Comment by Gannon001** [comment]
Sorry i don't understand.

I don't read table job or job_grades

**Comment by elnax90** [comment]
as you can see in the in the attached images my job_grades table is the one that gcphone is reading.
i tryed changing the  ( "number": "patrao", "display": "cardealer", " ) from the job table 
but it doesnt work.
why is gcphone reading the values from job_grades?
im very confused!!

{
      "number": "patrao",
      "display": "cardealer",
      "icon": "/html/static/img/icons_app/psp.png"
    }

![tables](https://user-images.githubusercontent.com/43297772/56080639-71448080-5dfb-11e9-9edc-1eeaa043f99b.png)

@Gannon001 
thanks for your help!

**Comment by elnax90** [comment]
Im using this to add a favorite contact to a job that is a car dealer.
so if there's a player with the job cardealer online and someone try to contact him via the favorite contact in gcphone he will recieve a msg.

in the config i added:
{
"number": "cardealer", ------ this is the job label
"display": "boss", ------------this is the job name   
"icon": "/html/static/img/icons_app/psp.png"
}

but it doesnt work that way...
so i try with the job_name and label from job_grades table.

and gcphone worked.
the problem is my job grade label has multiple labels for same job for exemple:

job:cardealer label:novice
job:cardealer label:boss

and in the phone this looks wrong.

im hoping you did understand my problem now!
@Gannon001 
thanks

**Comment by Gannon001** [comment]
I don't read any table except gcphone table.

For munber of society, i catch event 'esx_phone:registerNumber' in esx_addons_gcphone

Exemple for cardealer:
https://github.com/ESX-Org/esx_vehicleshop/blob/ccf027261b72984722c78901ac1f788ebc933123/server/main.lua#L7

**Comment by elnax90** [comment]
do i need esx_phone instaled for gcphone catch that?
TriggerEvent('esx_phone:registerNumber', 'cardealer', _U('dealer_customers'), false, false)
thanks

**Comment by Gannon001** [comment]
No need esx_phone
Send message to spécifique grade jobs is not possible currently.
But you can create this feature.

**Comment by elnax90** [comment]
I dont need gcphone to work with job grades.
i need it to work with normal jobs.
if i uncomment that line i get this error on server console

==== Enregistment du telephone cardealer = Clientes do STAND
![error2](https://user-images.githubusercontent.com/43297772/56081300-ae147580-5e03-11e9-8fcf-48875077ea31.png)

**Comment by Gannon001** [comment]
try this

https://github.com/N3MTV/gcphone/issues/93#issuecomment-481295023
