### ISSUE TITLE
Phone animation work's but no display

### ISSUE THREAD

**Issue by ceyhuncakir** [N3MTV/gcphone#106]
Hi, When i open my phone the only thing that works is the player model animation and no display. Is there any fix for this problem. Thanks

**Comment by sazo2300** [comment]
Are you sure your resource is named "gcphone" and the sql requirements are in your db?

**Comment by lnno** [comment]
I'm having the same issue as well.

**Comment by ceyhuncakir** [comment]
The gcphone folder is in resources, esx_addons_gcphone is in esx folder. Both sql are improrted without errors. In config order: esx,phone,jobs.

**Comment by Gannon001** [comment]
Source package, required build for use, 
Download compiler version => https://github.com/N3MTV/gcphone/releases

**Comment by ceyhuncakir** [comment]
Thanks man

**Comment by Redrock69** [comment]
You could help me.  That's the problem for me.  No display.  The db is my phone number.  No error message.  What could be the problem?
