### ISSUE TITLE
Problème avec les appels RTC (turnserver)

### ISSUE THREAD

**Issue by FrBillyD** [N3MTV/gcphone#11]
Hello !
Premièrement, merci pour cette grosse mise à jour ! Ca nous fait bien gagner du temps et c'est cool de voir toujours autant de partages 😄 

J'ai un petit soucis avec les appels RTC. L'appel passe bien jusqu'au serveur, mais Vue.js génère une erreur :
![image](https://user-images.githubusercontent.com/4552702/41609788-e24c05b4-73eb-11e8-9fa3-0b93ccd67513.png)

Côté serveur "turnserver" :
![image](https://user-images.githubusercontent.com/4552702/41609869-0d207e8c-73ec-11e8-8415-5715b2c3aac2.png)

Quelqu'un aurait une idée ? Le système est-il fonctionnel chez quelqu'un ?

Notre soucis c'est que lors d'un appel, on entend pas la communication en jeu... Seuls les deux personnes qui communiquent peuvent parler et s'entendre. En tant qu'admin, c'est gênant, on ne sait pas si les gens parlent HRP ou pas... Le meilleur moyen est de passer par le système RTC, sauf si je me trompe 😕 

Merci d'avance !

**Comment by Gannon001** [comment]
Salut,

Le système par WEBRTC, n'est pas encore fonctionnel.
Elle le serra dans une futur MAJ.

**Comment by FrBillyD** [comment]
Ok super ! Je reste à l'écoute alors ! Je connais pas trop pour le moment donc je serais incapable de terminer 🤦‍♂️  😂  

Merci vraiment pour ton taff !

**Comment by Gannon001** [comment]
La dernière version fonctionne avec RTC. Bonne chance

**Comment by FrBillyD** [comment]
Wow !! J'ai envie de tester ça dis donc ! 😄 
Merci beaucoup ! Je te dis si c'est bon de mon côté 😉

**Comment by FrBillyD** [comment]
Parfait ! T'es un Dieu ! 👌 Un big GG pour le taff ! ❤️
