### ISSUE TITLE
Walking and talking with mouse support

### ISSUE THREAD

**Issue by wrettro** [N3MTV/gcphone#110]
Would there be a way to allow walking during a phone call only?

**Comment by foxoak** [comment]
will be nice if it's possible disable the Nuifocus when accept a call

**Comment by foxoak** [comment]
It will be nice if is possible disable Nuifocus when accept a call

**Comment by sazo2300** [comment]
This is not something that needs a fix. NuiFocus overrules any keyboard input you have. Bind talk to one of your mouse side buttons to fix this. This is a gta limitation, not the fault of the mod (look at any server that uses a mouse based phone)

You could disable it while in a call, but ultimately, you should rebind talk key to something non input sensitive, to avoid problems like these using any resource 👍
