### ISSUE TITLE
Mouse Control

### ISSUE THREAD

**Issue by SATTAGAMES** [N3MTV/gcphone#112]
When I try to send a message with the mouse control option enabled, the text box to enter the message can not be typed.
Then I have to go in settings and turn off the mouse control so I can type.
Would you have some way to fix this?
http://prntscr.com/nco69g

**Comment by foxoak** [comment]
type direct in the phone with the mouse support on.

**Comment by 5-c-o** [comment]
This still appears to be an issue with the latest version. You cannot type directly into the phone when contacting Ambulance/Police via the Phone app (the version which sends GPS.)
