### ISSUE TITLE
Talk While Mouse On Issue

### ISSUE THREAD

**Issue by itzdevilz97** [N3MTV/gcphone#113]
If mouse is on, when people call you and if u have it on, you cant press "N" to talk, any fix for this?

**Comment by sazo2300** [comment]
This is not something that needs a fix. NuiFocus overrules any keyboard input you have. Bind talk to one of your mouse side buttons to fix this. This is a gta limitation, not the fault of the mod (look at any server that uses a mouse based phone)

**Comment by itzdevilz97** [comment]
So how can i change the default value to to use keyboard instead mouse
