### ISSUE TITLE
Hide the HUD when we take a picture

### ISSUE THREAD

**Issue by dragonir44** [N3MTV/gcphone#114]
Hi, i would like to hide all the HUD when i use the photo app but i don't know how can i do that
(i am on an ESX framwork so i want to hide esx_status bar and es_extended hud)

**Comment by HalCroves** [comment]
Hi,
You can check a part of a code here : https://github.com/HalCroves/gcphone/blob/mysql-async-3.x/gcphone/client/photo.lua

This code function but you need to adapte this for your usage.

@Gannon001 Si ce message est gênant pour toi, je le supprimerais.

**Comment by Gannon001** [comment]
@HalCroves Aucunement ;)

Merci ;)

**Comment by dragonir44** [comment]
yop merci du partage :)
Mais j'ai quand même un petit problème (remarque j'ai surement encore fait n'importe quoi) mais quand j'appui sur enter pour cacher le HUD je peux plus le remettre ni quitter le mode photo

**Comment by dragonir44** [comment]
En bidouillant un peu j'ai réussi à palier à mon problème encore merci à toi @HalCroves :)
