### ISSUE TITLE
Changing the config.json but nothing changed appears ingame

### ISSUE THREAD

**Issue by SHOKiDOKi** [N3MTV/gcphone#115]
Hey,

As the Title is saying, I have the Problem that I edit the config.json I made an fresh install of gcphone and esx_addons_gcphone also deleting server cache und restarting, I Changed only the Letter from "J" to "P" on the Police section but Ingame it's always the Letter "J" how can that be?

My start order:
esx_addons_gcphone
gcphone
jobs etc.

**Comment by Gannon001** [comment]
Check if you config.json is valid => https://jsonformatter.curiousconcept.com/
```json
  "defaultContacts": [{
      "number": "ambulance",
      "display": "Ambulance",
      "icon": "/html/static/img/icons_app/bank.png"
    },
    {
      "number": "police",
      "display": "Police",
      "backgroundColor": "blue",
      "letter": "P"
    }
  ],
```

**Comment by Gannon001** [comment]
I guess that's is fixed
