### ISSUE TITLE
what about set up html folder ?

### ISSUE THREAD

**Issue by K3IDB** [N3MTV/gcphone#118]
how to place src_htmlPhone in resources plugin folder or where ?
i tried but when i press its empty but animate play phone

**Comment by pedrogmz** [comment]
You have to build the html folder yourself. Make sure you have npm installed and then go to your src_htmlPhone folder and type:
`npm install`
`npm run build`

and it will generate an "html" folder in /resources/gcphone/

Or you can use the release version, which includes the html folder. You can find the builds here: https://github.com/N3MTV/gcphone/releases

**Comment by K3IDB** [comment]
TY

**Comment by K3IDB** [comment]
> You have to build the html folder yourself. Make sure you have npm installed and then go to your src_htmlPhone folder and type:
> `npm install`
> `npm run build`
> 
> and it will generate an "html" folder in /resources/gcphone/
> 
> Or you can use the release version, which includes the html folder. You can find the builds here: https://github.com/N3MTV/gcphone/releases

can you tell me about install npm ?
i cant understand

**Comment by K3IDB** [comment]
new version cant download in release

**Comment by K3IDB** [comment]
and i already type 
npm install
npm run build

but i dont see html folder 
maybe can you upload "html" folder from newest version generate for me ?

**Comment by K3IDB** [comment]
![image](https://user-images.githubusercontent.com/49761561/56475490-1eca2a80-64b3-11e9-9f23-dd0a6783249d.png)

is it newest version ?
