### ISSUE TITLE
Chat Issue

### ISSUE THREAD

**Issue by itzdevilz97** [N3MTV/gcphone#122]
With mouse activated sometimes the chat get buged and clients need ro restart the fivem to use back the chat.
how can i change the default value to use keyboard instead mouse

**Comment by Gannon001** [comment]
in DarkChat ?

The keyboard is by default in the next release. It is a mistake

**Comment by Garik0w** [comment]
It is also happening on the phone and without pressing any key, try to talk by chat, it must be restarted to solve the problem.

**Comment by Gannon001** [comment]
Do you have a method to reproduce this bug?

**Comment by Garik0w** [comment]
If u change key to F1, push it, and later try chatting

**Comment by Dhannyjsb** [comment]
> 
> 
> Do you have a method to reproduce this bug?

Open your phone, and try to chat (default is T) you can't chat , and you cant close chat menu until you restart the game.

**Comment by mike7671** [comment]
> Do you have a method to reproduce this bug?

1. Open phone
2. Open chat
3. Chat becomes bugged (can't type anymore)

Right now you can only fix by restarting the "chat" resource, hope you find a fix soon.

**Comment by Dhannyjsb** [comment]
> 
> 
> > Do you have a method to reproduce this bug?
> 
>     1. Open phone
> 
>     2. Open chat
> 
>     3. Chat becomes bugged (can't type anymore)
> 
> 
> Right now you can only fix by restarting the "chat" resource, hope you find a fix soon.

Not only Chat, Almost all resource using UI with HTML have problems. EX: InventoryHUD.
for a temporary solution you can edit client.lua gcphone, and Close gcphone with T (chat), so, If you open gcphone and press T, you will close gcphone, not open Chat menu.

**Comment by SliderKP** [comment]
this is planned to be solved??

**Comment by Dhannyjsb** [comment]
@SliderKP . you can try add this code to cient.lua 

`function TooglePhoneOff() 
  menuIsOpen = false
  SendNUIMessage({show = false})
  PhonePlayOut()
end`
and
 `Citizen.CreateThread(function()
  while true do
    Citizen.Wait(0)
    if takePhoto ~= true then
      if IsControlJustPressed(1, 245) and menuIsOpen == true then
        hasPhone(function (hasPhone)
          if hasPhone == true then
            TooglePhoneOff()
          end
      end)
    
	end
  end
 end
end)`
