### ISSUE TITLE
Suggestion: ability to copy the phone number

### ISSUE THREAD

**Issue by VerguchtNiels** [N3MTV/gcphone#127]
Hello,

Great phone, but it would be nice if we were able to copy the phone number in the message. When people drive too fast, we get a message with their phone number and their speed at that time. We then need to type this value somewhere else to copy and paste it in our phone number checker.

Having an option to copy the phone number when we highlight the message would be nice.

Thanks in advance

**Comment by Gannon001** [comment]
Maybe soon :)
