### ISSUE TITLE
Problem with job calls

### ISSUE THREAD

**Issue by SliderKP** [N3MTV/gcphone#128]
Hi, maybe my problem is caused by my low English, I hope not, and try to repeat the changes more than 3 times to see if I was wrong, but it does not seem.

In my list of scripts gcphone and addons are located BEFORE the jobs (esx, jobs, esx_policejob, esx_ambulancejob, esx_mechanicjob)

and when you want to call an authority or medic, the call does not arrive.

I found this post:
https://forum.fivem.net/t/tutorial-gcphone-adding-calls-and-job-messages/177904

and although I think it's an old post, I think it's obsolete, although I'm not sure try to follow the guide more than 1 time

Then I will leave images on certain data that I think will be useful, I hope you can help me from now thanks.

Database JOBS:
http://puu.sh/Di7wz/947913ed23.png

Original gcphone/html/static/config/config.json (fragment)
http://puu.sh/Di7x0/9e850591c6.png

Scripts list:
http://puu.sh/Di7D6/f4ef7144e0.png

**Comment by bellane** [comment]
Also having this problem.

**Comment by Gannon001** [comment]
Yop,

When you start server, do you have
> ==== Enregistrement du telephone ambulance => Alerte Ambulance
> Started resource esx_ambulancejob

When player send message to jobs
> Appels sur un service non enregistre => numero : xxxxxxxxxxx

**Comment by brezeyt** [comment]
I see that ^^ in my console, but isnt working to call companies

**Comment by bellane** [comment]
Im getting this error
`get phone to 1 
Error running system event handling function for resource esx_addons_gcphone: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server.lua:119: attempt to index a nil value (global 'ESX') 
stack traceback: 
server.lua:119: in function 'getPhoneNumber' 
server.lua:76: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow' 
citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
`

**Comment by Gannon001** [comment]
Vocal call ou Message call ?

**Comment by bellane** [comment]
Im trying to make it so when you call police it'll send a distress signal. Also the ambulance distress signal doesn't work.

**Comment by bellane** [comment]
> Vocal call ou Message call ?

I added you on Discord. My name is Ethan.

**Comment by Gannon001** [comment]
For distress signal 2 options

* Edit all jobs with distress
Exemple for esx_ambulancejob (client/main.lua)
```lua
-- function SendDistressSignal()
-- 	local playerPed = PlayerPedId()
-- 	local coords = GetEntityCoords(playerPed)

-- 	ESX.ShowNotification(_U('distress_sent'))
-- 	TriggerServerEvent('esx_phone:send', 'ambulance', _U('distress_message'), false, {
-- 		x = coords.x,
-- 		y = coords.y,
-- 		z = coords.z
-- 	})
-- end

function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords	= GetEntityCoords(playerPed)
	ESX.ShowNotification(_U('distress_sent'))
	TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), {
		['x'] = coords.x, 
		['y'] = coords.y
	})
end
```

* OR Add this code in esx_addons_gcphone (/server.lua)
```lua
RegisterServerEvent('esx_phone:send')
AddEventHandler('esx_phone:send', function(number, message, _, coords)
  local source = source
  if PhoneNumbers[number] ~= nil then
    getPhoneNumber(source, function (phone) 
      notifyAlertSMS(number, {
        message = message,
        coords = coords,
        numero = phone,
      }, PhoneNumbers[number].sources)
    end)
  else
    print('esx_phone:send | Appels sur un service non enregistre => numero : ' .. number)
  end
end)
```

**Comment by Gannon001** [comment]
The orignal problème is with distress signal ?

**Comment by bellane** [comment]
What about police? How do I make it so they get a notification?

**Comment by SliderKP** [comment]
Hi sorry for the time, im not getting notificattion from github.

i tried:
OR Add this code in esx_addons_gcphone (/server.lua)
RegisterServerEvent('esx_phone:send')
AddEventHandler('esx_phone:send', function(number, message, _, coords)
  local source = source
  if PhoneNumbers[number] ~= nil then
    getPhoneNumber(source, function (phone) 
      notifyAlertSMS(number, {
        message = message,
        coords = coords,
        numero = phone,
      }, PhoneNumbers[number].sources)
    end)
  else
    print('esx_phone:send | Appels sur un service non enregistre => numero : ' .. number)
  end
end)
 and not working, i going to try the first option in minuted and going to edit the comment if needed.

**Comment by SliderKP** [comment]
Hi sorry for the time, im not getting notificattion from github.

ambulance job working(messages and distress), now how can i do with the job esx_policejob?
@Gannon001

**Comment by SliderKP** [comment]
@Gannon001 no way to fix jobs calls?
distress and messages works but not calls...

**Comment by NickRobinYT** [comment]
> Yop,
> 
> When you start server, do you have
> 
> > ==== Enregistrement du telephone ambulance => Alerte Ambulance
> > Started resource esx_ambulancejob
> 
> When player send message to jobs
> 
> > Appels sur un service non enregistre => numero : xxxxxxxxxxx

I do not see that but gcphone and the addons are started before the job

**Comment by thedreamteam2** [comment]
i have the same problem that police and ambulance dont recieve message i hope somebody can help

**Comment by overdam** [comment]
I have same issue. Help please!

**Comment by Blackwave78** [comment]
change order to start gcphone and stuff before job

**Comment by Magnemice** [comment]
gcphone is broken af

**Comment by kailesh07** [comment]
bro gc phone 2.4 not recieving distress ambulance job pls help

**Comment by kailesh07** [comment]
@SliderKP  bro how  did u fix ambulance distress message
