### ISSUE TITLE
Send Dispatches 

### ISSUE THREAD

**Issue by thefuell** [N3MTV/gcphone#13]
Hey, 

first thing you did an awesome job!

but i have some problems the dispatches to the Police is workin, but all other services dont work they dont get any dispatches, and when you call the Police i hear the ring but see no info window how i can accept calls^^ 

by the second fix phone is the same, but no ringing there and no info window^^

is there any solution? 

merci beaucoup!

**Comment by Gannon001** [comment]
You need tu configure /html/static/config/config.json
