### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by lvp11** [N3MTV/gcphone#130]
Is twitter finished already? Or at least working somehow?

Thanks!

**Comment by Gannon001** [comment]
Yes is finish.

**Comment by lvp11** [comment]
Thanks

**Comment by 85Compacom** [comment]
Hello I've set up everything including twitter.sql etc to my database and when I start my server everything looks good but in-game when I try to send a tweet it is  not working
note: I also tried to create an account for Twitter Its not creating what should I do

**Comment by Blackwave78** [comment]
same not working
