### ISSUE TITLE
Format number direct call

### ISSUE THREAD

**Issue by bobsnunhes** [N3MTV/gcphone#142]
Hello i´m currently having a problem when i call a player directly without adding him on my contacts. I though the problem it´s because you cant send the number with "-" when you do a direct call... How can i format the number before player do a direct call or add a new contact on the list (if he add´s with no "-")

**Comment by foxoak** [comment]
you can.

Check the config.json file and look for something about numberfranceformat and change true to false or vice versa.

**Comment by bobsnunhes** [comment]
thank you so much man ! problem solved
