### ISSUE TITLE
Help compiling source folder?

### ISSUE THREAD

**Issue by lnno** [N3MTV/gcphone#147]
Can someone assist me with compiling the source folder so I can update GCPhone. I believe Gannon updated it so you can use push to talk with mouse control and I'm also having an issue where people can't talk to each other on the phone so I'm hoping updating the script might help but I'm unsure on how to do so.

**Comment by Gannon001** [comment]
install nodejs & npm https://nodejs.org/
clone git
open terminal in gcphone/src_htmlPhone
> npm install
> npm run build

**Comment by lnno** [comment]
Thanks homie.
