### ISSUE TITLE
Only mouse control

### ISSUE THREAD

**Issue by sonn1n** [N3MTV/gcphone#148]
how to set the phone to use only mouse?

**Comment by Gannon001** [comment]
Set mouse to true 
https://github.com/N3MTV/gcphone/blob/9139bc922967875ebdf4fa03fec632691993e8c0/src_htmlPhone/src/store/modules/phone.js#L12

Remove options for mouse in parametre.vue

**Comment by sonn1n** [comment]
I did it, however unsuccessfully.
You can release a phone version with only use mouse to control ?
Thank you.

**Comment by sonn1n** [comment]
dont work for me :(
