### ISSUE TITLE
Tuto RTC

### ISSUE THREAD

**Issue by WalterWhite84** [N3MTV/gcphone#15]
Bonjour Gannon serait-il possible que tu fasse un petit tuto rapide sur l’installation et le paramétrage d'un serveur TURN sur windows s'il te plait ? Pour que l'on puisse par la suite continuer d'utiliser cette alternative car une fois la beta fermer nous seront obliger de repasser sur le serveur gta et se serait dommage ayant une machine j'aimerais beaucoup pourvoir continuer d'utiliser se système alternatif car je trouve cela essentiel de pouvoir se faire entendre et être entendu dans le jeu en étant au téléphone cela apporte du réalisme :) Merci par avance

**Comment by Gannon001** [comment]
Je ne ferrais pas de tuto désoler, mais voila des piste:

Mon sevrer TURN actuelle est sur un VPS OVH sous linux (debian) a 3€ /mois.
J'utilise coturn => https://github.com/coturn/coturn.
Pas besoin de compiler depuis les sources, fait juste un 
>apt-get install coturn

Apres vous trouverais de l'aide sur la config sur le wiki de dépôt ou via d'autre site comme par exemple : 
https://www.nomachine.com/AR07N00894

Mettez a jour le config.json :)

**Comment by WalterWhite84** [comment]
Merci beaucoup Gannon cela me suiffit amplement pour reussir a me debrouiller :) Merci beaucoup pour cette aide et pour se telephone qui est simplement enorme ! :)

**Comment by driouach88** [comment]
slt Ganon . jais un petit problem . pour une raison , le Serveur RTC march seulement avec des joueurs mais pas tt le monde . je serais reconnaissant si tu fais copier ton  turnserver.conf  .
jutilise coturn avec ubunto . merci d avance
