### ISSUE TITLE
How to take photos?

### ISSUE THREAD

**Issue by rodier** [N3MTV/gcphone#151]
hi
i tried find keyboard binding for photo.. tried all keybs and nothing..
how to take photo with it?
Thanks

**Comment by rodier** [comment]
Also, please how to change default language for every new user? Thanks

**Comment by foxoak** [comment]
"Enter" to sent the photo, must be in messages to work.

The camera APP is a "fake" cam.

**Comment by rodier** [comment]
Thanks
