### ISSUE TITLE
Disabling Auto Login

### ISSUE THREAD

**Issue by brandinarsenault** [N3MTV/gcphone#159]
Hello!

I'm aware that the credentials of a Twitter user are stored in local storage and thats what drives most of these functions, but with our multi character system, when you switch between characters its logging you into an account on another character that wouldn't belong to you. 

I need to accomplish two tasks with this requirement and I'm not sure the best way to do it. Just some insight and help would be appreciated.

-Disable autologin (I can handle the re-login component of it on character switch)
-Modify darkchat so it is done on a split basis rather than by the overall user

Thank you,
Brandin.

**Comment by Gannon001** [comment]
No easy soluce 

The data is stored on the player's side. Here =>
https://github.com/N3MTV/gcphone/blob/f1ba98f2a6b5423af71c2e117762c57e09cda116/src_htmlPhone/src/store/modules/twitter.js#L5-L7

Disable autologin change to
```js
 twitterUsername: undefined, 
 twitterPassword: undefined, 
 twitterAvatarUrl: undefined, 
// ...
```
Or better, save server side and send them to the reader. But that requires some changes.

Same for darkchat

**Comment by brandinarsenault** [comment]
Thanks @Gannon001 for your reply. If I come up with a good solution I will post it so it is available for others.
