### ISSUE TITLE
Some one pls help

### ISSUE THREAD

**Issue by ninenite** [N3MTV/gcphone#162]
![dbd366aa407bfb840408eaf066e50b5c](https://user-images.githubusercontent.com/19632855/57298087-8a3f0980-70fb-11e9-8de9-a478b58e1fbc.png)

how to do this that big problem because my language not work on text box / someserver used normal box and it works

thanks

**Comment by Gannon001** [comment]
Enable mouse for use input html.

**Comment by ninenite** [comment]
@Gannon001  give me how to pls 


thank a lot sir
