### ISSUE TITLE
Messages box aren't showing and mouse control not working

### ISSUE THREAD

**Issue by ZeProf2Code** [N3MTV/gcphone#166]
Hello, I'm running this, I activated the mouse control and I can't do anything, and even when I don't have the mouse control activated, when I try to send a message or enter something (for example in the Twitter username box) it's not showing anything.

Thanks for your help!

**Comment by Gannon001** [comment]
Hi, 

No error ? You're the only one to mention me this problem

**Comment by ZeProf2Code** [comment]
Hi, no there isn't any errors. I'm not the only one that had this problem. I saw multiple others issues with the same problem but when I run the NodeJS App in my browser, it's working but not in game. And it's not only me, it's all the players

**Comment by ZeProf2Code** [comment]
Oh, in the client console, I have errors like this : `nui://phone/html/index.html#/twitter/view:0, Uncaught (in promise) #<Object>`

**Comment by Gannon001** [comment]
Do you have this problem with the build I provide?

**Comment by ZeProf2Code** [comment]
yes

**Comment by CAHenson** [comment]
I am experiencing the following: messages are not sending / receiving on the front-end but saving to database. they do appear on re-connect.

**Comment by ZeProf2Code** [comment]
Any ideas?

**Comment by ZeProf2Code** [comment]
Working, when renaming the files it's not working... Sorry for disturbing!

**Comment by Otisnfur** [comment]
@ZeProf2Code What files did you rename that caused it to stop working?

**Comment by ZeProf2Code** [comment]
I renamed gcphone to phone and esx_addons_gcphone to esx_addonphone
