### ISSUE TITLE
walk stuck again in 2.19

### ISSUE THREAD

**Issue by shinneygin** [N3MTV/gcphone#167]
on call can't walk and press any key for "N" key voice. I can't fix it, please help

**Comment by Gannon001** [comment]
Oups :D
Thx

**Comment by shinneygin** [comment]
![image](https://user-images.githubusercontent.com/50460827/57477732-8827a700-72c3-11e9-83d1-012d1e111f6b.png)

and stuck on send a photo in the message menu. THXXX

**Comment by Gannon001** [comment]
> ![image](https://user-images.githubusercontent.com/50460827/57477732-8827a700-72c3-11e9-83d1-012d1e111f6b.png)
> 
> and stuck on send a photo in the message menu. THXXX

In 2.19 or 2.20 ?

**Comment by shinneygin** [comment]
both sir

**Comment by Gannon001** [comment]
Ok normally is good
