### ISSUE TITLE
Webrtc setting up but still no voice

### ISSUE THREAD

**Issue by Hankaws** [N3MTV/gcphone#171]
0: Config file found: /root/../etc/turnserver.conf
0: Listener address to use: 158.69.206.0
0: Config file found: /root/../etc/turnserver.conf
0: Domain name:
0: Default realm: thaiinter.com
0: ERROR:
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0: WARNING: cannot find certificate file: turn_server_cert.pem (1)
0: WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: WARNING: cannot find private key file: turn_server_pkey.pem (1)
0: WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: Relay address to use: 158.69.206.0
webrtc enabled and when calling it does pop up send cadidate   12      W3siY2FuZGlkYXRlIjoiY2FuZGlkYXRlOjIxMzgzOTM0OTMgMSB1ZHAgMjExMzkzNzE1MSAxOTIuMTY4LjAuNCA2MzY1NiB0eXAgaG9zdCBnZW5lcmF0aW9uIDAgdWZyYWcgMCtxOSBuZXR3b3JrLWNvc3QgOTk5Iiwic2RwTWlkIjoiMCIsInNkcE1MaW5lSW5kZXgiOjB9XQ==
TO      3 in server console but still no voice. Help please

**Comment by Hankaws** [comment]
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
only issue now

**Comment by daniel96rk** [comment]
You haven't set it up properly, and this is still not a gcphone issue.

**Comment by Hankaws** [comment]
Now i set it up properly still not working thou no error or anything only Relay address to use: 158.69.206.0 but still doesnt work

**Comment by daniel96rk** [comment]
I'm sorry, but if you have it set up properly then it should be working, as it has worked for me and many others.

**Comment by Hankaws** [comment]
I followed all the instructions but cant get it working, could you help me?

**Comment by daniel96rk** [comment]
This should contain everything you need. I cannot help you with issues related only to coturn. 

https://github.com/N3MTV/gcphone/blob/master/__INSTALL_COTURN_HELP.md

**Comment by Hankaws** [comment]
That is what I followed and it doesnt work.

**Comment by daniel96rk** [comment]
When you open an issue and ask for help, you need to provide all the information you can. I need to see your configuration and i want to see how you set it up inside config.json (gcphone). You can't just say that it's not working because that doesn't provide me with any information about your problem.

**Comment by Hankaws** [comment]
I did in the first post and I set up all userpassword. It does run Relay address to use: 158.69.206.0 and nothing more and when calling it does pop up send cadidate 12 W3siY2FuZGlkYXRlIjoiY2FuZGlkYXRlOjIxMzgzOTM0OTMgMSB1ZHAgMjExMzkzNzE1MSAxOTIuMTY4LjAuNCA2MzY1NiB0eXAgaG9zdCBnZW5lcmF0aW9uIDAgdWZyYWcgMCtxOSBuZXR3b3JrLWNvc3QgOTk5Iiwic2RwTWlkIjoiMCIsInNkcE1MaW5lSW5kZXgiOjB9XQ== but no voice...

**Comment by Hankaws** [comment]
"useWebRTCVocal": true,
  "RTCConfig": {
    "iceServers": [{
      "urls": ["turn:vps239025.vps.ovh.ca"],
      "username": "thaiinter",
      "credential": "espada"
    }]
  },

**Comment by daniel96rk** [comment]
"urls": ["turn:vps239025.vps.ovh.ca"],

Are you sure that is the right url? You might want to try and put the IP of your VPS there instead.

**Comment by daniel96rk** [comment]
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

Use this to test your WEBRTC server.

**Comment by Hankaws** [comment]
add server?
or

**Comment by Bartixxx32** [comment]
https://github.com/N3MTV/gcphone/pull/240
