### ISSUE TITLE
Job calls not working?

### ISSUE THREAD

**Issue by LifeGoal** [N3MTV/gcphone#178]
Hi!
I'm using ESX for my server and want to use the "call to society" feature. I've set up so it should call to number police, but it won't work for some reason. I call, but the police on the server doesn't get any calls.

Is there anything wrong I am doing? I've the latest update.

**Comment by daniel96rk** [comment]
Is gcphone started before the jobs?

**Comment by LifeGoal** [comment]
Yes it's! It seems like the people in the jobs doesn't recieve the call even tho it is "police" and not anything else.

**Comment by LifeGoal** [comment]
Can add some more information to the issue. I've noticed that the calls goes into the database, but nothing comes up for the reciever, as in the workers for the job. Is there anything more that I have to do, more than changing the phone number for the job? Seems strange..

**Comment by XenSide** [comment]
I believe you missunderstood how it works, it's not gonna call every member of said society, but a stationary phone.
For example when you call the police you will hear a phone ringing in the waiting room of the police department, you can answer from there
