### ISSUE TITLE
How to start src_htmlPhone?

### ISSUE THREAD

**Issue by joxim2** [N3MTV/gcphone#179]
Cann someone help me about it i downloaded that script but how can i use that part of this script?

**Comment by daniel96rk** [comment]
Download gcphone from the release section instead. https://github.com/N3MTV/gcphone/releases.

**Comment by joxim2** [comment]
> Download gcphone from the release section instead. https://github.com/N3MTV/gcphone/releases.

i downloaded it but idk how to start that src_htmlPhone is that requires coturn or something? I dont know how to use coturn
