### ISSUE TITLE
Moving GCPhone Twitter Notifications

### ISSUE THREAD

**Issue by Delexical** [N3MTV/gcphone#185]
Hello,
Let's start off by saying that I have only just started to learn LUA, CSS and JS in the past couple of weeks.
I'm trying to attempt to change the twitter notifications to use the chat that I am using.
The chat I'm using is [reknits_chat](https://github.com/Reknits/reknits_chat), a remake of esx_rpchat.
Anyways, I have successfully 'removed' the default twitter notification by going into:
gcphone/html/static/css/app.css and adding opacity to the notification:
```
.notification[data-v-64f456c2]{
    width:450px;
    background-color:rgba(29,161,242,.6);
    color:#fff;
    padding:8px 16px;
    margin-bottom:8px;
    border-radius:6px;
    opacity: 0
}
```
In addition to this, I have gone into gcphone/server/twitter.lua and have edited the gcPhone:twitter_postTweets event as such.

```
RegisterServerEvent('gcPhone:twitter_postTweets')
AddEventHandler('gcPhone:twitter_postTweets', function(username, password, message)
  local sourcePlayer = tonumber(source)
  local srcIdentifier = getPlayerID(source)
  TwitterPostTweet(username, password, message, sourcePlayer, srcIdentifier)
  TriggerClientEvent('chat:addMessage', -1, {
      template = '<div style="padding: 0.8vw; margin: 1.0vw; background-color: rgba(62, 174, 244, 0.7);border-radius:12px;">^0<i class="fab fa-twitter" size: 7x></i> @{0}^0: {1}</div>',
      args = { username, message }
  })
end)
```
Ultimately, it does hide the original notification but I am having issues figuring out how to utilise the notification settings that are set through the phone.
https://i.imgur.com/523kauW.png
I found some code relating to 'gcphone_twitter_notif' in gcphone/html/static/js/app.js but I am unsure how to implement it.

Any help or guidance would be appreciated, let me know if you need any additional information.

Thanks.

**Comment by HalCroves** [comment]
Check here : https://github.com/N3MTV/gcphone/issues/129
