### ISSUE TITLE
Fichiers html

### ISSUE THREAD

**Issue by GrapsZ** [N3MTV/gcphone#19]
Salutations !

Dans un premier temps je tiens à vous dire que vous avez réalisé un travail de malade ! C'est grave propre.
J'aurais une question également. Est il possible de "compiler" ( je ne sais pas si le terme est bon ) les fichiers présents dans src_htmlPhone avec node js ?

Je ne connais pas du tout node, et pour le coup j'aurais aimé une petite précision à ce sujet.

Merci et encore bravo !

**Comment by Gannon001** [comment]
Hop,

Wep c'est le but justement.
Ils sont déjà compiler dans la parti release => https://github.com/N3MTV/gcphone/releases

Si vous voulez les modifier et compiler, voici les étapes:
```
Télécharger & install node
Ouvrir un terminal dans le dossier src_htmlPhone
Lancer les commandes suivantes
  #> npm install
  #> npm dev (Pour les étapes de modification)
  #> npm run build (Compilation)
```

**Comment by GrapsZ** [comment]
Merci pour la réponse !

Justement tout ce que tu indique je l'ai effectué. Le build me permet de consulter les fichiers via : localhost:8080

Mais par exemple, je ne trouve pas l'emplacement de app.js, app.css etc... Je les ai effectivement téléchargé via les release, mais le "design" du téléphone n'est pas le même.

Tu saurais ce qui cloche ?

**Comment by Gannon001** [comment]
J'ai pas comprit le design du téléphone n'est pas le même. Il est comment .?

Sinon une fois build, les fichiers se place directement dans ./../resources/gcphone/html/...

**Comment by GrapsZ** [comment]
Alors je vais essayer d'être plus explicite.

Je télécharge tes sources. J'ouvre nodejs avec l'invite de commande. je fais un cd, pour aller dans le dossier src_htmlPhone ( il se trouve sur mon bureau directement, le soucis est ici ?? )

Ensuite je fais donc les commandes que tu m'as donné qui sont aussi dans le readme, et je ne trouve pas les fichiers.

Niveau design regarde : 
![1](https://user-images.githubusercontent.com/33883629/41967923-265fd2b8-7a03-11e8-9cc5-5cc6bcd3aed7.jpg)
![2](https://user-images.githubusercontent.com/33883629/41967924-2675409e-7a03-11e8-90bb-20d274232f78.jpg)

J'ai changé les couleurs des messages reçus ( ils étaient en vert ). En haut il n'y a pas l'affichage du "réseau et de la batterie" comme sur tes screens. La partie pour rédiger un message n'est pas la même non plus.

Pour la composition du numéro c'est pareil. Il n'y a pas non plus la barre supérieure ( réseau & batterie "

**Comment by GrapsZ** [comment]
Après avoir tout refait correctement, tout fonctionne et j'ai tout compris.
Merci encore pour le super taf :)
