### ISSUE TITLE
No Alerts/Notifications

### ISSUE THREAD

**Issue by xVelns** [N3MTV/gcphone#195]
Hello.

I'm using the latest gcphone and esx_addons_gcphone.

gcphone and esx_addons_gcphone are started right after es_extended.
I can send messages, I can receive and hear calls, however I don't receive any message notifications/alerts.
The Twitter alerts are working.

In config.lua the - ShowNumberNotification has been set to true

Could you please assist?
If you need any files, please let me know.

Regars,
Velns

**Comment by xVelns** [comment]
It was a DB problem at the end. That is why no notification came through.

**Comment by osdeibi** [comment]
@xVelns what was the solution?

**Comment by xVelns** [comment]
I don't recall clearly now, but I think it was in MySQL, phone_messages (or something like that). And one init variable should have been set to 36. (I think it was owner).

Hope it helps!
