### ISSUE TITLE
I can't hear what they said while calling

### ISSUE THREAD

**Issue by hung1806vn** [N3MTV/gcphone#198]
My server base on esx server.

I just disable the webrtc. What am i missing ? Does it need esx_voice ? 
I'm using vVoice

If you guys have any idea pls help me.

Thanks in advance

**Comment by Bartixxx32** [comment]
https://github.com/N3MTV/gcphone/pull/240

**Comment by HighLifeServers** [comment]
how did you fix it

**Comment by Linder96** [comment]
How you guys fix it ??
