### ISSUE TITLE
GCphone all white

### ISSUE THREAD

**Issue by OvertimeDev-Random** [N3MTV/gcphone#208]
When I open the phone it is all white and I get an error when I restart the gcphone resource 
![image](https://user-images.githubusercontent.com/42265006/58760713-4fb16c80-8501-11e9-98a5-7dca10a6d910.png)

**Comment by 777sven** [comment]
Did you got it Fixed? I got the same problem. Just a Plain white screen.

**Comment by LabasPabas** [comment]
It happens for me when i message for any of jobs.
