### ISSUE TITLE
GG Gannon !

### ISSUE THREAD

**Issue by Cr4zZyBipBiip** [N3MTV/gcphone#21]
Nice work ! Comme le premier GCPhone sous FX, tu as fait un super taf' de ouf 💯 !

Voilà, c'était juste pour te dire GG !

Et aussi... pense à limiter le standard si, et seulement si, les personnes sont flics ^^

Je l'ai pas encore écrit mais je vais PR si je le fais avant toi

**Comment by Gannon001** [comment]
Merci ;) sa fait plaisir !
