### ISSUE TITLE
twitter photo

### ISSUE THREAD

**Issue by gksknight** [N3MTV/gcphone#211]
http://prntscr.com/nyj2io

photo error when I share link
The above picture has sample

nui://gcphone/html/static/js/vendor.js:6 Uncaught ( in promise ) #<Object>

why am I getting this error

**Comment by gksknight** [comment]
problem solved.

**Comment by mrrpstaff** [comment]
i'm having the same problem. could you help me?

**Comment by mrrpstaff** [comment]
> problem solved.

i'm having the same problem. could you help me?

**Comment by sertacdncl** [comment]
Hİ how can you solved it @gksknight ?
