### ISSUE TITLE
how to send photo with sms ? 

### ISSUE THREAD

**Issue by insayd10** [N3MTV/gcphone#216]
can some body explain it ?

**Comment by berdancanyet** [comment]
can you show us the way?

**Comment by insayd10** [comment]
sure

**Comment by berdancanyet** [comment]
Would like to see.

**Comment by insayd10** [comment]
any where to contact?

**Comment by berdancanyet** [comment]
dc: BcY#7193

**Comment by AllCitySor** [comment]
Hello @insayd10 im also interested. Can you show me please ? This is my discord tag : 

Capi#2003

**Comment by 23Linc** [comment]
Hi, im also interested on how to do it. Do you want my discord tag?
