### ISSUE TITLE
Duplicate distress sigals to ambulance

### ISSUE THREAD

**Issue by metopatel** [N3MTV/gcphone#225]
Hey I have gcphone installed with esx_ambulance and when players send distress signals, ems is getting them 2 times instead of one. I checked the code for duplications of the signal sending but there aren't any, any ideas to why this would happen?

**Comment by WeiZTD** [comment]
esx_addons_gcphone\server.lua
change line 28

            if alert.coords ~= nil then
            TriggerClientEvent("gcPhone:receiveMessage", tonumber(k), smsMess,alert.coords)
            else
            TriggerClientEvent("gcPhone:receiveMessage", tonumber(k), smsMess)
            end

**Comment by metopatel** [comment]
> esx_addons_gcphone\server.lua
> change line 28
> 
> ```
>         if alert.coords ~= nil then
>         TriggerClientEvent("gcPhone:receiveMessage", tonumber(k), smsMess,alert.coords)
>         else
>         TriggerClientEvent("gcPhone:receiveMessage", tonumber(k), smsMess)
>         end
> ```

I appreciate the reply but i'm still getting duplicates
