### ISSUE TITLE
Bank problem

### ISSUE THREAD

**Issue by calmitup** [N3MTV/gcphone#23]
Hi.

The Bank-app do not work. It always show 0. Even if i enable bank.lua code in client folder.

Tips for bank: Should be nice if you could send money to other players true the app.

**Comment by GrapsZ** [comment]
The script is very much like that and is basically only a phone script. If you want the bank application to work, it's up to you to code it. Everything is specified in the files. So it's up to you to do it. You must avoid waiting for everything to fall into your hands!
