### ISSUE TITLE
Instagram scriptini veriyorum artık ( FOTOĞRAFLI TWİTTER)

### ISSUE THREAD

**Issue by insayd10** [N3MTV/gcphone#235]

**Comment by mrrpstaff** [comment]
Do you sell the source files?

**Comment by insayd10** [comment]
@mrrpstaff  yes

**Comment by mrrpstaff** [comment]
Gimme a price

**Comment by insayd10** [comment]
@mrrpstaff 90 $

**Comment by RayRayden** [comment]
You did a great job mate. Me and my management team spoke about your scripts and we made a decision about it. We want to buy your script. Can we deal? I added you on Discord my nickname is Rayden.

**Comment by RayRayden** [comment]
Especially we are interested on your script's Search Files. Rather than script, We can only buy your search files.

**Comment by marfixdev** [comment]
Marfix#7786 discorddan eklersen içerigi konuşabiliriz 64/64 çeken aktif bir sunucum var

**Comment by lilfuchs** [comment]
Lmao, selling scripts on a github issue.

**Comment by insayd10** [comment]
> Lmao, selling scripts on a github issue.

Are every repo open source on git ?

**Comment by lilfuchs** [comment]
> > Lmao, selling scripts on a github issue.
> 
> Are every repo open source on git ?

I'm just saying anyone that buys a fivem script has a chance of having there server blacklisted since they broke fivem TOS. not to mention your probably breaking github tos
