### ISSUE TITLE
track for the bank

### ISSUE THREAD

**Issue by rodrii-rms** [N3MTV/gcphone#24]
When we call the telephone (F2) we call the event that obtains the balance and that to the client that we have of track in bank.lua .. it would have to work not?

Later I'll try this and I'll tell you

**Comment by rodrii-rms** [comment]
well my idea failed sadly or I'm not getting it right

Pressing F2 I call the event that gives me the balance of the user with ESX

`RegisterNetEvent('gc:bankbalance')
AddEventHandler('gc:bankbalance', function ()
    local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
    balance = xPlayer.getAccount('bank').money
    TriggerClientEvent('gc:gobalance', balance)
    print(balance)
end)`

And of course this event calls an event that the client sends the data

`RegisterNetEvent('gc:gobalance')
AddEventHandler('gc:gobalance', function(a)
	local a = a
	print("BANK" ..a)
end)
`

for some reason the server event does not call the client's event .. (checked by the print)

**Comment by Gannon001** [comment]
>TriggerClientEvent('gc:gobalance', balance) 

>TriggerClientEvent('gc:gobalance', source, balance)

**Comment by rodrii-rms** [comment]
I feel stupid .. awkward mistake .. thanks for the help

already working, although this way fulfills the function. but I think it would be better that when someone opens the application do the query because you may have a fault if someone sends money with the phone open

https://gyazo.com/db7fdfd9a5e256b750fee95b44cb3ca3

**Comment by Th3Cha0s** [comment]
Mind sharing the fix?

**Comment by rafakid** [comment]
share the fix plis
