### ISSUE TITLE
Question about Mouse Control ?

### ISSUE THREAD

**Issue by SSnarKW** [N3MTV/gcphone#272]
Hi, Need to set mouse control for all player

that code i edit

> html/static/js/app.js
> mouse:"true"===window.localStorage.gc_mouse

> client/client.lua
> local useMouse = true

new player when he open gcPhone mouse not Active he controls by Arrow Key
i need set mouse for All player can you tall me were files to fix it

**Comment by sonnydg** [comment]
> Hi, Need to set mouse control for all player
> 
> that code i edit
> 
> > html/static/js/app.js
> > mouse:"true"===window.localStorage.gc_mouse
> 
> > client/client.lua
> > local useMouse = true
> 
> new player when he open gcPhone mouse not Active he controls by Arrow Key
> i need set mouse for All player can you tall me were files to fix it

https://github.com/N3MTV/gcphone/blob/f1ba98f2a6b5423af71c2e117762c57e09cda116/src_htmlPhone/src/store/modules/phone.js#L12

this is TRUE and compile.

```
client/client.lua
local useMouse = true
```
this is ok.

**Comment by SSnarKW** [comment]
@sonnydg 

that code i edit before but it's not working

example :-
a new player start in my server and he open gcPhone controls by Arrow Key 
not by mouse !!

but i will see how can fix that code
