### ISSUE TITLE
Fonctionnement ?!

### ISSUE THREAD

**Issue by Yodalesage29** [N3MTV/gcphone#28]
Salut, j'ai suivi le read.me mais je ne comprends pas celui du fichier html ^^ Je ne m'y connais pas du tout en terme de java script^^ 

Pour le moment, si j'ai bien compris il faut : 
-Prendre les deux fichiers dans ressources, mettre le src_... dans le gcphone et le renommé html
-Ensuite il faut mettre dans le __ressource tout les fichiers qui sont dans le dossier html 
-start le gcphone puis le esx_addons_gcphone ? 

Un petit d'aide pour me guider sur la suite ou pour me reprendre si jamais je fais quelques choses mal ^^ Merci d'avance !

**Comment by Gannon001** [comment]
Non
Télécharge la version pré-compiler ici => https://github.com/N3MTV/gcphone/releases
start gcphone 
start esx_addons_gcphone (optionnel / esx seulement & apres les métier esx_job )

Have fun
