### ISSUE TITLE
After pressing F2(the open phone key) nothing happens

### ISSUE THREAD

**Issue by mja00** [N3MTV/gcphone#31]
When I press F2 nothing happens, the phone never opens nor does an animation play. I've downloaded the files and installed and started them in the right order. I've even tried other F keys and pretty much any key on the keyboard.

**Comment by rodrii-rms** [comment]
did you download the latest releases? Or did you compile the files?

I think the last one is a bit outdated

**Comment by PrayGayben-Qc** [comment]
where i put the src_htmlPhone folder ?
