### ISSUE TITLE
Phone not showing up anymore during animation

### ISSUE THREAD

**Issue by LethalKingz** [N3MTV/gcphone#322]
Whenever you take the phone out, the animation still happens but the phone model itsself doesn't seem to spawn. You're just holding an invisible phone.

Looked through the code but didn't really see anything that could cause the issue.
Any ideas? Saw this happening on a couple of servers already.

**Comment by sabiaryl** [comment]
Hello, i don't know if this a fix for you, but i tried to replace the phone model name by the phone model hash : 

So, i replaced : 
`local phoneModel = 'prop_npc_phone'`

by

`local phoneModel = -1038739674`

and now the phone is not invisible anymore.

**Comment by LethalKingz** [comment]
> Hello, i don't know if this a fix for you, but i tried to replace the phone model name by the phone model hash :
> 
> So, i replaced :
> `local phoneModel = 'prop_npc_phone'`
> 
> by
> 
> `local phoneModel = -1038739674`
> 
> and now the phone is not invisible anymore.

This seemed to fix it. Quite stupid of me that I didn't think of this myself.
Thanks for the help though!
