### ISSUE TITLE
Some people can not make or receive calls.

### ISSUE THREAD

**Issue by calmitup** [N3MTV/gcphone#33]
For 80%, the phone works perfectly. However, for some people, it is not possible to make or receive calls. Everything else works for them. When they press ENTER to call, nothing happens. They get this wrong when they check F8 in FiveM.

https://imgur.com/a/i5jbUf8

Best Regards Calm

**Comment by calmitup** [comment]
I solved the problem. NVM

**Comment by Ultrunz** [comment]
care to share?

**Comment by EGUltraTM** [comment]
same here
