### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by Fluffyss** [N3MTV/gcphone#330]
so im having this error
![image](https://user-images.githubusercontent.com/63029838/80304602-5f8c0c00-87b7-11ea-8bb7-8332924756a3.png)

with this database table phone_messages
![image](https://user-images.githubusercontent.com/63029838/80304619-7df20780-87b7-11ea-9c95-0833f31ab3a4.png)

with this part of (stock) code that i didnt touch.
![image](https://user-images.githubusercontent.com/63029838/80304641-982be580-87b7-11ea-97bf-b3b0f1375760.png)

first, whenever i send a message, the SQL error exist both job related as player to player.

second in the sql error he is trying to save the receiver as the transmitter (sender). That number in the error was the person i've send the message to, it wasnt mine.
from my basic knowledge of SQL he cant save the reveiver as NULL because he cant find the receiver.

Thank you in advance.

**Comment by Fluffyss** [comment]
UPDATE: 
![image](https://user-images.githubusercontent.com/63029838/80315238-8fa6cf80-87f6-11ea-9ebd-533535eb0a27.png)
Message got saved in database BEFORE the sql error and the phone crashing because of the SQL error.
Strange enough the reveiver and transmitter are switched?

**Comment by Fluffyss** [comment]
No idea how, but suddenly it was fixed...

**Comment by SubwooferNL** [comment]
i have the same issue but mine is not fixed lol

**Comment by iiAlphaWolf** [comment]
Same here
