### ISSUE TITLE
J'entends rien ou on m'entend pas

### ISSUE THREAD

**Issue by YSKK-STUDIO** [N3MTV/gcphone#348]
Salut Jonathan.

J'ai un petit soucis avec le Gcphone. 

Tout fonctionne, quand on m'appel je peux décrocher, mais quand je parle ou que la personne parle aucun son.. On entend rien. Tu peux m'aider stp ? 👍

Merci d'avance.

**Comment by BTNGaming** [comment]
Hey, I'm not him, but he basically retired from gcphone from my understanding, I've taken over updating and such but on a new github link, (Not officially yet, but i've been the one fixing/updating it for the last year. If you want to join up in our discord, I run the official ESX Support Discord for V1.2(final) and older now. https://discord.me/rid

I've added a gcphone-support channel their, where we can try to help with your issues. =]

**Comment by YSKK-STUDIO** [comment]
Résolve...

Just create a Webrtc server and put him on the config file..
