### ISSUE TITLE
Bug v1 gcphone 

### ISSUE THREAD

**Issue by TankHord** [N3MTV/gcphone#35]
j'ai un problème

comme plusieurs serveur rp apparament ils ont la v1 de gcphone mais avec la v2 sa marche et v1 sa ne marche pas la console me dit daller dans server.lua la linge 18 je compare les deux fichier et c'est les même exactement a la linge 18 COMMENT FAIRE!!!!!!

https://cdn.discordapp.com/attachments/455728276061683723/472116696308776970/Capture.PNG

je crois que j'ai pas le bon sql

**Comment by FrBillyD** [comment]
Tout d'abord, **bonjour**.

Tu trouveras les infos que tu cherche ici : https://github.com/brouznouf/fivem-mysql-async
Ce n'est pas un problème de script en soit mais plutôt quelque chose qui n'est pas trouvé. En l'occurrence, ici, il s'agit de la valeur `MySQL`.

_Bonne journée et bon courage._

**Comment by TankHord** [comment]
mais pourquoi avec la v2 ça marche

**Comment by TankHord** [comment]
et avec la valeur MySQL je ne sait pas trop quoi faire dsl mais je suis un nouveau dev
