### ISSUE TITLE
Notfications for jobs dont work.

### ISSUE THREAD

**Issue by Antioxy** [N3MTV/gcphone#353]
Hi, 
notifi. dont work for all jobs, 
Error code: 
SCRIPT ERROR: @esx_addons_gcphone/server.lua:20: attempt to concatenate a nil value (field 'numero')
> notifyAlertSMS (@esx_addons_gcphone/server.lua:20)
> callback (@esx_addons_gcphone/server.lua:72)
> ref (@esx_addons_gcphone/server.lua:133)
>  (@mysql-async/mysql-async.js:15543)

**Comment by BTNGaming** [comment]
in esx_addons_gcphone/server.lua change line 20's "numero" to "number" and see if that works.

**Comment by BTNGaming** [comment]
Was that the fix? Would be nice to know for future reference.

**Comment by BTNGaming** [comment]
If you closed it, what was the problem?
