### ISSUE TITLE
Hidden missed calls show's transmitter number

### ISSUE THREAD

**Issue by mfventura** [N3MTV/gcphone#355]
When you make a hidden call, if the reciever doesn't accept the call, the number of the transmitter appears on the "missed calls list". That happens because on server/server.lua has a bug where is asigned to MUN instead of NUM the "###-####".

**Comment by BTNGaming** [comment]
Thanks for the heads up, I will fix that in my version which will be fully released soon. We're revamping it and adding a TON of new bug fixes and adjustments to it, along with new styles and such.
