### ISSUE TITLE
Problème DarkChat

### ISSUE THREAD

**Issue by baalexan** [N3MTV/gcphone#41]
Bonjour,

Les messages dans le channel darkchat ne se range pas par jour et heure du coup, les messages sont mélangés et ne sont donc plus dans l'ordre décroissant.

J'ai des messages envoyé hier qui sont mélangés avec ceux d'aujourd'hui et ranger uniquement par l'heure d'envoie.

**Comment by JaroSound** [comment]
+++ Is there a fix?
