### ISSUE TITLE
The calls won't work...

### ISSUE THREAD

**Issue by KRILLE123** [N3MTV/gcphone#43]
Well, like in the title the calls won't work...

**Comment by Thaisen69** [comment]
I have the same struggle. Think it's a fiveM update i dont know? Would really like a fix

**Comment by revolt32** [comment]
Hi, has anyone found a solution to this problem?

**Comment by Helweg** [comment]
You will have to setup your own server to handle the webRTC

**Comment by KRILLE123** [comment]
Halweg, what do you mean? @Helweg

**Comment by revolt32** [comment]
Can you show us how you fix this problem ?

**Comment by Helweg** [comment]
@revolt32 I have explained what you should do, furthermore, it there has been linked a guide on how to set up the server in an already closed issue.

**Comment by joebopie** [comment]
@Helweg You haven't explained jack you have just been a arrogant nob like a lot of coders... So what closed issue how about link that instead of acting all superior...

**Comment by Helweg** [comment]
@joebopie How about you used the tiny little meatball inside of your head. How hard is it to use Google translate, to translate french, if you can't accomplish something like that, then you should be re-evaluating, wether or not you should be a developer.

**Comment by Helweg** [comment]
@joebopie So you have translated a lot of French mods, what a developer you are. How about you try to read through the code, and understand what is happening. It's people like you, that expect every thing to handed over to them on a silver plate, that make people not wanting to share anything.
But here is a hint, try to see if you can use your brain to figure it out:
config.json tells what server it is connecting to, it even says what protocol it is using.

**Comment by greybeardactual** [comment]
Being that I do not write code but I can learn by following directions. Could you point me to the webrtc server setup?  And maybe where in the code to fix it?  I'm new to building up a server but would appreciate the assistance!
