### ISSUE TITLE
Hello i want translate a phone i did it in 99% but can not find one can u please help me?

### ISSUE THREAD

**Issue by Bartixxx32** [N3MTV/gcphone#48]
Hello as in title im trying to translate phone...
I did it in 99% but last thing i cant find nowhere in code i hope for help 
Im trying find this
>>>De<<< #xxx-xxxx : message
and excatly im tryiong find this (De)
i hope for help
send image of this
https://i.imgur.com/HJi3k3l.png

**Comment by Gannon001** [comment]
Look here
https://github.com/N3MTV/gcphone/blob/074810694cf2fa9593d696aa05d5121993adf968/resources/esx_addons_gcphone/server.lua#L24

**Comment by Desiignne** [comment]
Jak ty to wszystko przetłumaczyłeś ? :/

**Comment by daffiestfrog41** [comment]
@Bartixxx32 Do you have the full GCphone translated and working?
