### ISSUE TITLE
Name from saved Contact is not being showed when calling

### ISSUE THREAD

**Issue by EGUltraTM** [N3MTV/gcphone#51]
Hi,

the we always see incunno (unknown) but we have the number saved in the contacts.

**Comment by xtrsyz** [comment]
unknown number when incoming call.

**Comment by xtrsyz** [comment]
still unknown number when incoming call.

**Comment by EGUltraTM** [comment]
still the same here.

using webrtc is also not working to show when you have the guy as a contact.

anything i forgot?
