### ISSUE TITLE
how i can install that?

### ISSUE THREAD

**Issue by Kuanaxd** [N3MTV/gcphone#55]
i dont now how to install, some one can explain me?

**Comment by PrayGayben-Qc** [comment]
Same here

**Comment by Albin323** [comment]
Download put in resources

start like this: 

start esx_addons_gcphone
start gcphone

If you do not understand then use https://forum.fivem.net and search for gcphone tutorial

**Comment by PrayGayben-Qc** [comment]
THat not a problem the problem is just because i don't know where to put src_htmlPhone :/
