### ISSUE TITLE
gcphone Can't seem to get calls or messages to work

### ISSUE THREAD

**Issue by rxduu** [N3MTV/gcphone#58]
So I have installed it correctly, it opens up, messages get sent through to Police and Ambulance. However, I can't call other players or send them messages. When calling, it does not even go to the calling screen.

Is there any way I can fix this, and if so, how?

**Comment by drawix** [comment]
me too

**Comment by Albin323** [comment]
Does it start like it should?

start esx_addons_gcphone
start gcphone

**Comment by Ffrankys** [comment]
You need to start gcphone BEFORE the jobs...

**Comment by AJCADamen** [comment]
So I have this problem, all jobs receive messages except mechanic. How can i fix this?

**Comment by AJCADamen** [comment]
Fixed

**Comment by FameMartijn** [comment]
How did you fix it?

**Comment by AJCADamen** [comment]
https://github.com/N3MTV/gcphone/issues/318

Read my comment

**Comment by MeynLP** [comment]
> So I have installed it correctly, it opens up, messages get sent through to Police and Ambulance. However, I can't call other players or send them messages. When calling, it does not even go to the calling screen.
> 
> Is there any way I can fix this, and if so, how?

How did you fix it? I have the same problem but I did not find any solution for this kind of problem. Thanks in advance.
