### ISSUE TITLE
 Problème avec l'ajout de contacts

### ISSUE THREAD

**Issue by Vertizer** [N3MTV/gcphone#60]
Bonjour, j'ai un problème, il n'y a aucun moyen d'entrer un numéro pour ajouter un contact

**Comment by Albin323** [comment]
Does it start like it should? I used Google translate i can't speak french

start esx_addons_gcphone
start gcphone

-------------------------------------------------------------------------------------------------------------------

Cela commence-t-il comme il se doit? J'ai utilisé Google Translate, je ne parle pas français
