### ISSUE TITLE
Couleur Bank / Color Bank

### ISSUE THREAD

**Issue by gusepe73** [N3MTV/gcphone#61]
Bonjour, encore un merci pour ce téléphone.

Je cherche un modifier la couleur de l'écriture de l'application **bank**. J'ai chercher coté CSS et Javascript mais je n'es rien trouver pour changer la couleur. Coté JavaScript j'ai essayer de changer les valeur telle que **#ff0000** ou autre que j'ai retrouver en rouge.

Si une personne pourrai m'orienter. 

Merci Cordialement

*****************

Hello, another thank you for this phone.

I am looking for a change the color of the writing of the **Bank** application. I look for CSS and Javascript side but I'm not finding anything to change the color. JavaScript side I try to change the value such as **#ff0000** or other that I find in red.

If someone can direct me. 

Thank you cordially

**Comment by Albin323** [comment]
Make a dev server and play around, i will do it when i get it to work fully and come back with an answer! :D
