### ISSUE TITLE
When Accept Call hear someone is calling

### ISSUE THREAD

**Issue by thefuell** [N3MTV/gcphone#62]
Bonjour!

i have the problem when someone is in call and you stand next to him you cant hear what he's talking.

Where i have to change that you can hear the person over the phone and the person next to you can hear what youre talking? 

and second thing gcphone is one of the best extensions for esx thank you soooo much!

**Comment by Albin323** [comment]
@thefuell What i know no plugins works with that, tho make a dev server and play around! :)

**Comment by thefuell** [comment]
Is there a possibility for the files for the webrtc Server to configure one?
