### ISSUE TITLE
 phone 

### ISSUE THREAD

**Issue by raptorkiller6** [N3MTV/gcphone#65]
I put the file as you say and the phone appears like this: c

https://gyazo.com/075fcca85e6ab55f30725842789ac434

**Comment by Albin323** [comment]
Do you start it like this?

start esx_addons_gcphone
start gcphone

**Comment by raptorkiller6** [comment]
Yes of course, fix the problem, but I see that it is only for ESX servers and it is not for VRP, one day you will get one for VRP
