### ISSUE TITLE
White screen after message

### ISSUE THREAD

**Issue by MpLLLL71** [N3MTV/gcphone#66]
I have a white screen each time when I have a new message.

http://image.noelshack.com/fichiers/2018/47/4/1542856302-1.jpg
http://image.noelshack.com/fichiers/2018/47/4/1542856306-2.jpg
http://image.noelshack.com/fichiers/2018/47/4/1542856309-3.jpg

**Comment by adbergerat** [comment]
Same problem, having this error client side : 
` nui://gcphone/html/static/vendors.js:1102, TypeError: Cannot read property '0' of undefined`

**Comment by adbergerat** [comment]
I resolve it using a fork of this repo : https://github.com/HalCroves/gcphone
I also needed to checkout 2.0 in your https://github.com/brouznouf/fivem-mysql-async/tree/2.0

**Comment by mirrox1337** [comment]
I got the same issue, my phone works on my local server but does not work on my zap hosted VPS?

**Comment by snakezdigital** [comment]
guys somebody can help me to install gcphone? i cannot call and after message i got white screen
