### ISSUE TITLE
Dispatch not working

### ISSUE THREAD

**Issue by AtomXGer24** [N3MTV/gcphone#67]
Hey,

I installed the GCPhone and everything is working properly. However I can´t get disptachs.
What I need to do?

Thanks

**Comment by murphyhf** [comment]
Same... My Phone stuck at Messages (dispatch)

**Comment by Ffrankys** [comment]
You need to start gcphone BEFORE the jobs...

**Comment by Strikerrr** [comment]
Heyy i have the same problem that i cant get dispatches from ambulance or police. the gcphone start before the jobs but it doesnt work. Can anyone help me please?
