### ISSUE TITLE
I can't hear person talking by phone

### ISSUE THREAD

**Issue by J8nko** [N3MTV/gcphone#76]
Hello!
When i call someone in game i can't hear him talking by phone, i can hear him only when i'm next to him. How can i repair it please help me!!

**Comment by Bartixxx32** [comment]
disable webrtc?

**Comment by MrArthurDev** [comment]
> disable webrtc?

Thanks for help man 👍

**Comment by ericb160** [comment]
where do i disable webrtc? thanks for any help
