### ISSUE TITLE
Comment caché des applications

### ISSUE THREAD

**Issue by Superordi45** [N3MTV/gcphone#81]
Bonjour, 
Je cherche a affiché des applications seulement pour la police par exemple
J'ai trouvé la fonction:
RegisterNetEvent('gcPhone:setEnableApp')
AddEventHandler('gcPhone:setEnableApp', function(appName, enable)
    SendNUIMessage({event = 'setEnableApp', appName = appName, enable = enable })
end)

qui apparemment sert a ça mais je ne trouve pas la fonction qui lui réponds dans les fichiers serveur.lua 

Comment faire ?

**Comment by Gannon001** [comment]
C'est le serveur qui doit envoyer la notification au client pour activer/deactiver une App.

```lua
-- Sa doit donner un truc comme ça
-- Le joueurs est de la police
TriggerClientEvent("gcPhone:setEnableApp", sourcePlayer, 'AppPolice', false)
```
