### ISSUE TITLE
Failed to compile with 6 errors

### ISSUE THREAD

**Issue by SomeGuyX** [N3MTV/gcphone#82]
What am I missing?
Trying to compile fresh repo (got all dependencies)
` ERROR  Failed to compile with 6 errors                                                                                                                                                                                              19:10:57

These dependencies were not found:

* @/components/Contacts/Contacts in ./src/router/index.js
* @/components/Contacts/Contact in ./src/router/index.js
* @/components/Messages/MessagesList in ./src/router/index.js
* @/components/Messages/Messages in ./src/router/index.js
* @/components/Messages/MessageContactsSelect in ./src/router/index.js
* @/components/Parametre/Parametre in ./src/router/index.js
`

**Comment by SomeGuyX** [comment]
These folders doesn't start with capital letter :) Linux is picky :)

**Comment by Gannon001** [comment]
Thx, this is fix now <3
