### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by lvp11** [N3MTV/gcphone#83]
Hey!

Any chances of being able to translate this?
https://forum.fivem.net/uploads/default/original/3X/6/8/68ebc3293259531030b5446066d67a859d50779e.png

Thanks!

**Comment by Gannon001** [comment]
If you need translate " De #XXXX: ... "

Look here
https://github.com/N3MTV/gcphone/blob/3389fad56d41b5e6adfd74572e527ff6399a3257/resources/esx_addons_gcphone/server.lua#L24


If you want change mecano, change the number in jobs script (not tested)
Exemple
https://github.com/CMDTelhada/fxserver-esx_mecanojob/blob/e9438fa1be68546a29c3ff1933b7eb231011cceb/server/main.lua#L15

**Comment by lvp11** [comment]
Yeah, it breaks the script, already tried that...
There's any other way?

Thanks for your time and help!

**Comment by Gannon001** [comment]
Try this new version
Set defaultContacts in config.json

[gcphone.zip](https://github.com/N3MTV/gcphone/files/3035789/gcphone.zip)

**Comment by lvp11** [comment]
You are a legend, worked like a charm.
Another question, it's possible to make the phone a item?
Like, you need the phone item to use the phone. Got it?

(sorry for my bad english, i'm Brazilian).

**Comment by Gannon001** [comment]
If you use esx

comment line 32 - 34 and 38 - 39 in client.lua
Uncomment the line 46 - 65 in client.lua
Uncomment the line 27 - 42 in server.lua

**Comment by lvp11** [comment]
I should register phone on a script or i just need to add "phone" item to my db?

Thank you for your awesome work, you're a legend.

**Comment by Gannon001** [comment]
Yes add phone item in your base

**Comment by lvp11** [comment]
Awesome.

May i can get you Discord? I want to talk with you about some resources.

**Comment by Gannon001** [comment]
No sry

**Comment by lvp11** [comment]
Ok, thanks
