### ISSUE TITLE
No Icons on homepage

### ISSUE THREAD

**Issue by TrollikCz** [N3MTV/gcphone#84]
Hello i installed update on my server and now i dont have any icon in home page ...

**Comment by Gannon001** [comment]
Hello

Any error ?
Upload capture if possible.

**Comment by TrollikCz** [comment]
I have only SQLite error on server start ... nothing more

**Comment by TrollikCz** [comment]
![Screenshot_148](https://user-images.githubusercontent.com/46824730/55507305-aad8f700-5657-11e9-8895-4f1b8e68cd6f.png)

**Comment by TrollikCz** [comment]
![Screenshot_149](https://user-images.githubusercontent.com/46824730/55507384-d6f47800-5657-11e9-83c9-eb85c17eb187.png)
And this is in my config ...

**Comment by Gannon001** [comment]
Maybe update mysql-async
https://github.com/brouznouf/fivem-mysql-async

This part of the configuration is correct

**Comment by TrollikCz** [comment]
i have the latest version of mysql-async

**Comment by Gannon001** [comment]
Ok is SQLite error, not mysql-async.
Cache is clear ? else send me all config.json
Sinon envoyez moi le fichier config.json

**Comment by TrollikCz** [comment]
I dont know how but i fixed it

**Comment by Gannon001** [comment]
Oky :D
