### ISSUE TITLE
Send GPS Coordinates for players sending to players is not working. 

### ISSUE THREAD

**Issue by BlueDreammm** [N3MTV/gcphone#85]
Send GPS Coordinates for players sending to players is not working.

**Comment by BlueDreammm** [comment]
The Service Calls GPS is working just fine. but sending gps coords from a person to a person is not.

**Comment by Gannon001** [comment]
that work correctly in my local server.
But i am alone i send meself message.

I have a little trouble understanding your explanation. I'm not good at English: s

Etape check
 * Right Arrow => Show option SEND GPS is OK ?
 * Press enter => Message is send ? you receive feelback ?
 * Select message GPS: XX.XX, XX.XX, press enter. Show option set GPS is OK ?
 * Press enter, GPS set in the map is OK ?


Have you changed some files ?

**Comment by Gannon001** [comment]
Probleme solve ?

**Comment by DannyMadani** [comment]
Select message GPS: XX.XX, XX.XX, press enter. Show option set GPS is OK ? gps not ok
