### ISSUE TITLE
Ambulance distress signal not sending GPS coordinates !

### ISSUE THREAD

**Issue by JeanClode** [N3MTV/gcphone#88]
Hi,

Everything related to the new GcPhone works perfectly.

The only thing that doesn't seem to be working right now is the Distress signal call for the ambulance service when a player is down.

Sending the distress signal will send a text message to EMS, yes, but it won't include the GPS coordinates as it should / used to do.

Here is the piece of code related to this ... if you can help anyhow..

```
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords	= GetEntityCoords(playerPed)

	ESX.ShowNotification(_U('distress_sent'))
	
	TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), PlayerCoords, {

		PlayerCoords = { x = coords.x, y = coords.y, z = coords.z },
	})
	
end
```

Thanks in advance

**Comment by Gannon001** [comment]
Try this, if don't work, i check tomorrow.
```LUA
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords	= GetEntityCoords(playerPed)
	ESX.ShowNotification(_U('distress_sent'))
	TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), {
		PlayerCoords = { x = coords.x, y = coords.y, z = coords.z },
	})
end
```

**Comment by Gannon001** [comment]
```LUA
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords	= GetEntityCoords(playerPed)
	ESX.ShowNotification(_U('distress_sent'))
	TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), {
		['x'] = coords.x, 
		['y'] = coords.y
	})
end
```

**Comment by JeanClode** [comment]
Thanks it somehow works again now. Very nice.

**Comment by ROGSLAYER** [comment]
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords	= GetEntityCoords(playerPed)

	ESX.ShowNotification(_U('distress_sent'))
	
	TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), PlayerCoords, {

		PlayerCoords = { x = coords.x, y = coords.y, z = coords.z },
	})
	
end

i have done both but still it doesnt work can you help somehow?

**Comment by nidhin45** [comment]
bro where did i paste this code

**Comment by Rage-Gaming** [comment]
bro not working!!!!!

**Comment by ZyphDev** [comment]
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords	= GetEntityCoords(playerPed)

	ESX.ShowNotification(_U('distress_sent'))
	
	TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), PlayerCoords, {

		PlayerCoords = { x = coords.x, y = coords.y, z = coords.z },
	})

**Comment by Gameadictive** [comment]
And is any way to don´t use a esx_phone or gcphone so you can do it standalone?

**Comment by MagzGaming** [comment]
does this work with qbcore
