### ISSUE TITLE
Fixed call ? WebRTC isn't working

### ISSUE THREAD

**Issue by PwnedCax** [N3MTV/gcphone#91]
Please let update for resolve this  bug ...

**Comment by Gannon001** [comment]
The default rtc server in the config is close. Use other server.

**Comment by PwnedCax** [comment]
Have you a server it's work ?

**Comment by Gannon001** [comment]
No sry,
You can use coturn (https://github.com/coturn/coturn)

**Comment by PwnedCax** [comment]
i try it with coturn , ... and i don't understand how if work

**Comment by DevMinkh** [comment]
https://www.webrtc-experiment.com/docs/TURN-server-installation-guide.html#reTurnServer
I'm useing reTurn, it's easy to install and you can use gcphone with it.

LG

**Comment by KingRyuShin** [comment]
The problem with coturn or return is that it use linux or ubuntu only..
Anyone has one with windows ?

**Comment by Gannon001** [comment]
Maybe this => https://github.com/pion/turn
