### ISSUE TITLE
In call i dont hear other player.

### ISSUE THREAD

**Issue by Thirew** [N3MTV/gcphone#92]
Hello i using esx and if i call someone we cannot hear other one, i have disabled   "useWebRTCVocal": false, how to fix it please ?

**Comment by Gannon001** [comment]
You need to use webRTC for calling & listener other.

**Comment by sazo2300** [comment]
I have webRTC true but still hear nothing :(

**Comment by RiddiK1337** [comment]
uhm hey iam using gcphone + tokovoip and i can hear some players on the phone and some players i cant hear, how can i fix it? and sorry for my bad english...
