### ISSUE TITLE
send messages to police, gps

### ISSUE THREAD

**Issue by Thirew** [N3MTV/gcphone#93]
Hello if i send message to police or ambulance example "hello i need help and there is cordinates" and send cordinates, but people with ambulance or police job didnt receive it

**Comment by Gannon001** [comment]
From favortie menu is OK ?

If you need send message from "Message", add this try code in esx_addons_gcphone/server.lua

```LUA
RegisterServerEvent('gcPhone:sendMessage')
AddEventHandler('gcPhone:sendMessage', function(number, message)
    local sourcePlayer = tonumber(source)
    local identifier = getPlayerID(source)
    if PhoneNumbers[number] ~= nil then
      getPhoneNumber(source, function (phone) 
        notifyAlertSMS(number, {
          message = message,
          numero = phone,
        }, PhoneNumbers[number].sources)
      end)
    end
end)
````

let me know

**Comment by Thirew** [comment]
still didnt worked :/  only put this on esx_addons_Gcponhe in gcphone i didnt need add something?

**Comment by Gannon001** [comment]
esx_addons_Gcponhe  start before esx_jobs ?

**Comment by Thirew** [comment]
Yes

**Comment by Thirew** [comment]
please..

**Comment by Gannon001** [comment]
I need you server.cfg, ambluance script folder, gcphone script folder for more investigate.

**Comment by Thirew** [comment]
Sorry okay,

**Comment by Thirew** [comment]
where i can send you it ?

**Comment by Thirew** [comment]
i need sending message in contacts to ambulance, mechanic, police, cardealer, taxi

**Comment by Gannon001** [comment]
User discord => Gannon#0626

**Comment by Gannon001** [comment]
Discord => Gannon#0626

**Comment by Thirew** [comment]
hello, its worked

**Comment by Finleyyy** [comment]
Still not working for me, added @Gannon001 on Discord.

**Comment by Fluffyss** [comment]
@Gannon001 doesnt work here either. I've added you on Discord aswell.

**Comment by mrstruggle93** [comment]
also need help with GPS location i've you send an message to the mechanic, taxi etc
