### ISSUE TITLE
Html folder missing

### ISSUE THREAD

**Issue by wrettro** [N3MTV/gcphone#95]
Html folder is missing from the version with the twitter app.

**Comment by Gannon001** [comment]
No html folder is found. 
Or I'm not looking at the good place.

Link ?

**Comment by wrettro** [comment]
Both these versions of gcphone have it, but they have none of the twitter stuff in it. I'm currently experiencing a white screen when trying to use the twitter app and I'm assuming it's because of the missing html folder.

https://github.com/BTNGaming/btn_gcphone/tree/master/gcphone
https://github.com/HalCroves/gcphone/tree/mysql-async-3.x/gcphone

**Comment by wrettro** [comment]
I'm currently using the N3MTV version of gcphone with the twitter app, my issue was that when opening the twitter app I just got a blank screen.

**Comment by Gannon001** [comment]
Did you run the twitter.sql file?

**Comment by wrettro** [comment]
absolutely, I have all 3 sql tables in, twitter_accounts, twitter_likes, twitter_tweets, are in there.

**Comment by wrettro** [comment]
In your version where would the html/static/ file path be that is in the resource file?

**Comment by wrettro** [comment]
well that was dumb of me, thank you so much for your help
