### ISSUE TITLE
Mysql Connection Codes?

### ISSUE THREAD

**Issue by PiAdam314** [N3MTV/gcphone#98]
we couldn't find mysql connection codes in any files. how to connect and run sql codes like basic.sql and twitter.sql in our server without connection?

**Comment by Gannon001** [comment]
Run manually sql file. With heideiSQL or commande line.

gcphone require
 * essentialmod https://github.com/kanersps/essentialmode
 * mysql-async https://github.com/brouznouf/fivem-mysql-async
